name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Checkout data branch
        uses: actions/checkout@v4
        with:
          ref: "data"
          path: "data"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv pip install --system --requirement requirements.txt

      - name: Test
        run: |
          python3 test.py data/
